ethereum-cdap/cohort-zero

README.md

- stubs out the "suggested reading" section.
- adds a "contributing" section.

Stub out suggested reading section

---

README.md

Expand the FAQ a little with a few common questions.

Expand the FAQ with a few questions/answers

---

README.md

Add an invite link to the R&D discord.

Add R&D discord invite link

---

README.md

Added links pinned in #apprenticeship-program

recommended reading added in readme

---

README.md
stage-0-getting-started.md
stage-1-project-discovery.md
stage-2-project-exploration.md
stage-3-project-planning.md
stage-4-project-execution.md

Stub out some documents for filling out the program structure.

Stub out program structure

---

notes/piper.md
stage-0-getting-started.md
stage-1-project-discovery.md

Partially flesh out stage 1 instructions.

partially flesh out stage 1

---

notes/francesco.md

adding project notes for Eth1 specs and EIP-1559 on py-evm

add notes and project ideas

---

README.md

Added some useful questions answered by Piper in the R&D discord.

Expand FAQ questions

---

stage-0-getting-started.md

I am of the opinion that this is essential to anyone starting out with the Ethereum protocol. I've used these docs countless times!

Added link to JSON-RPC Wiki

---

notes/aaryamann.md

- Added potential research topic on core-developed state channels

Updated notes

---

notes/owl.md

Notes by @sblOWPCKCR

---

notes/muhd.md

muhd initial notes

---

notes/aaryamann.md

- Added devp2p notes & Extra on Kademlia Tables

Add Devp2p Notes

---

stage-0-getting-started.md

Added Ethereum basics, future of Ethereum, ethereum research subsections. Not sure if these are the best headers for subsections just a suggestion!

Added More to Recommended Reading + Subsections

---

notes/evan.md

Need to finalize with external links/readings.

Project ideas draft

---

README.md

@pipermerriam I've added a few more FAQs that I found useful from reading the Discord history. Feel free to merge what of this you think is useful for other applicants.

Add additional FAQ from Discord

---

stage-0-getting-started.md

Added
- conceptual overview (something I found extremely helpful to get the greater picture)
- ecosystem portal (a great starting point to get lost in the rabbit hole)
Updated
- JSON RPC documentation (afaik there is an ongoing effort to reconcile different json rpc implementations of clients and document this on the official ethereum.org site. So maybe we should link this instead of the older eth.wiki source)

Added some "Ethereum Basics" material

---

notes/milan.md

This PR adds my notes about areas of interest.

Adding milan.md

---

notes/ogenev.md

My topics of interest and useful links.

Ognyan's topics of interest and links

---

notes/mikeferris.md

Created `notes/mikeferris.md` for my notes.

Add notes on interests and projects

---

stage-0-getting-started.md

Added more subsections and some more links to resources. 
I hope this list can be a great resource to learners. 
I add a Proof of Stake stub that people can fill in with links.

Added more subsections 

---

stage-0-getting-started.md

I found the yellow paper a little complex to grasp and started searching for few alternative resources and found Vitalik's presentation.
Although it is not too technical, but enough to get a basic understanding of the Ethereum's architecture.

Adding Vitalik's presentation in the stage-0 section

---

stage-0-getting-started.md

includes a minor formatting fix

Adds Sharding and PoS links.

---

notes/AndrewC.md

First pass at some notes and thoughts on areas of interest.

Andrew C notes (Op Codes and EVM properties)

---

notes/ogenev.md

Update some links and define some problems and questions

Update some links and define some problems and questions

---

notes/iauns.md

Notes are a WIP mostly containing reference links.

Add Ethereum notes from iauns

---

notes/Nhlanhla.md

I am making a transition to Web3 Development, I believe this will be very helpful for my transition.

Add Nhlanhla's notes

---

notes/defipunk.md

Add some potential ideas for @defipunk, and related background reading material:
-  the portal network,
- more general statelessness work
- gas limit coordination, 
plus a few other links and potential ideas.

Add project ideas and background links for defipunk

---

README.md
program-faq.md
program-meta.md
stage-1-project-discovery.md

fixes #46 
This PR does a few things.
- Separate the FAQ
- Create a "Program Meta" for housing some information that doesn't fit anywhere else
- Flesh out better descriptions of what constitutes a good project.
- Remove a bunch of "double spaces after periods", a habit leftover from learning to type back in the 90's

updates and further fleshing out of program material

---

stage-0-getting-started.md

The one on stack overflow has been compressed and is quite hard on the eyes.

Higher resolution pictures for conceptual overview diagram

---

README.md
stage-2-project-exploration.md

working to flesh out the stage-2 program details.

start fleshing out stage 2

---

notes/ogenev.md

Add portal network notes and update links

Add portal network notes and update links

---

notes/aaryamann.md

@rymnc I took the liberty of fixing a dead anchor link.

fix dead anchor link

---

notes/ogenev.md

Add potential projects

---

notes/ogenev.md

Update notes structure and add questions and actions

Update notes structure and add questions and actions

---

README.md
development-updates.md
program-meta.md

Add new document and structure for posting development updates.

add structure for dev updates

---

notes/Nhlanhla.md

Added links to my notes as resources

Resources for Nhlanhla's notes added

---

development-updates.md

Add link to CDAP blog post I wrote.

Link to first development update.

---

development-updates.md

First development update for https://github.com/ethereum-cdap/cohort-zero/issues/62.

Add development update for code chunk tracking

---

development-updates.md
notes/yingtong/update_1.md

Signed-off-by: therealyingtong <yingtong@z.cash>

`yingtong/update_1.md`: Add Development Update #1.

---

notes/alu.md

- stateless ethereum
- state expiry
- portal network

Angela's Notes

---

notes/potuz.md

Added a link to mammon's repo and will be maintaining my notes there in the form of code or in the design.md file to hint at what I am doing currently.

Added link to mammon's repo

---

development-updates.md

Added my name  to Development updates and add my notes to TOC

Add TOC and Development updates

---

development-updates.md

Adding portal network / chain history network development update

Mike's development updates

---

notes/Nhlanhla.md

Added Markle trees to my interests and few blog links about ZKPs

Added Markle trees and ZKPs links from blog iden3

---

development-updates.md

My latest update about ZKPs and Markle trees

Nhlanhla's latest updates

---

notes/Nhlanhla.md

Explaining core system Ethereum Virtual Machine

Add Nhlanhla's notes update(EVM)

---

development-updates.md

Sorry, I forgot to add these to my previous [PR](https://github.com/ethereum-cdap/cohort-zero/pull/113).

Added voith's updates to table of contents

---

development-updates.md

Added a development updates from Nhlanhla.md with links from my HackMD.io account

Development updates from Nhlanhla.md

---

notes/Nhlanhla.md

Discovered Ethereum SNAPSHOT Protocol trying to comprehend how Ethereum came be awesome as it is up-to-date. Trying to understand the Ethereum evolution as it is.

Added New devp2p

---

notes/Nhlanhla.md

In my quest to understanding the evolution of Ethereum,  I added the RLpx transport protocol on DEVP2P topic

Added the RLPx Transport Protocol on DEVP2P

---

showcase/README.md
showcase/piper.md

fixes #67 
Adds a section for candidates to showcase their work.

Add candidate showcase stuff

---

showcase/mohamedmansour.md

Added the two issues I worked on Cohort-Zero

Showcase Mohamed Mansour
